"""empty message

Revision ID: 0cde87bdbbaf
Revises: 6c015db2a51e
Create Date: 2019-08-17 10:48:43.119452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cde87bdbbaf'
down_revision = '6c015db2a51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('citi_nam', sa.String(length=50), nullable=True),
    sa.Column('citi_region', sa.String(length=50), nullable=True),
    sa.Column('citi_area', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search')
    # ### end Alembic commands ###
