"""empty message

Revision ID: cf761c2d108c
Revises: eeaf49d887f4
Create Date: 2019-08-18 23:50:11.514457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf761c2d108c'
down_revision = 'eeaf49d887f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('search', sa.Column('ref', sa.Text(), nullable=True))
    op.drop_column('search', 'citi_nam')
    op.drop_column('search', 'citi_region')
    op.drop_column('search', 'citi_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('citi_area', sa.VARCHAR(length=50), nullable=True))
    op.add_column('search', sa.Column('citi_region', sa.VARCHAR(length=50), nullable=True))
    op.add_column('search', sa.Column('citi_nam', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('search', 'ref')
    op.drop_column('search', 'description')
    # ### end Alembic commands ###
