"""empty message

Revision ID: eeaf49d887f4
Revises: 0cde87bdbbaf
Create Date: 2019-08-18 00:28:40.860806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaf49d887f4'
down_revision = '0cde87bdbbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NP', sa.Column('area', sa.Text(), nullable=True))
    op.add_column('NP', sa.Column('region', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NP', 'region')
    op.drop_column('NP', 'area')
    # ### end Alembic commands ###
